# Check out https://docs.codemagic.io/yaml/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: Android App
        scripts:
            - cd Covid19Tracker
            - ./gradlew assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk
